### ISSUE TITLE
Guard options

### ISSUE THREAD

**Issue by PlaidFoxSG** [spiderwebtr/isauth#3]
Looking forward to testing this out, but I would need an option to use "guard", for example: `Auth::guard('admin')->check()`

**Comment by emredipi** [comment]
Hello @PlaidFoxSG, thanks for feedback. This package is using only web guard for now. There is not any config file yet but it seems the package need a config file for this kind of customizations. If you add one, I can accept PR or I'll make it myself later. And can you please make star if you like it? This is my first open source repo.

**Comment by emredipi** [comment]
I added [`isAuth`](src/config/isAuth.php) config file. Check the readme.
