### ISSUE TITLE
remove laravel-medialibrary from examples

### ISSUE THREAD

**Issue by jayenne** [spiderwebtr/isauth#7]
Hi. the example you have uses Spatie's [Laravel-MediaLibrary](https://docs.spatie.be/laravel-medialibrary/v8/basic-usage/retrieving-media/) ( getFirstMediaUrl() ).

As this is not actually required by your code, you could use the $user->avatar (insert model's key for your user's profile image)

...then include the current laravel-medialibrary example as a helpful alternative for those use it.

**Comment by emredipi** [comment]
Thanks for the advise.  👍
