### ISSUE TITLE
publish to public/vendor

### ISSUE THREAD

**Issue by jayenne** [spiderwebtr/isauth#8]
Hi,
Just to follow the guidelines used of Laravel and others, would you please consider publishing your assets to public/vendor/spiderwebtr/ (lowercase) rather then to public/assets/SpiderWebtr

ty.

**Comment by emredipi** [comment]
There is not actually common way to do it. Some projects use "assets", some don't. Maybe I can add a setting to change default location. Would that be okay for you?
